version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ituser
      POSTGRES_PASSWORD: ituser

volumes:
  data:
